### ISSUE TITLE
Subscription error on settings page and error while starting a build

### ISSUE THREAD

**Issue by phagunbaya** [Shippable/support#1588]
Getting below error on the setting page

```
{"id":9999,"message":"Missing active subscriptionPlan","methodName":"getActivePlanBySubscriptionId|_getActivePlanBySubscriptionId"}
```

Builds are not triggered automatically and while manual trigger getting below error

```
{"id":3000,"message":"No access or object not found for :id 55886c9647a1ce0b00f01b51","methodName":"chkPermForId|_getBuildById"}
```

**Comment by travisn** [comment]
+1 on the errors mentioned above. I see build status, but can't trigger builds or update settings.

**Comment by blakeblackshear** [comment]
+1 this is preventing builds for us as well

**Comment by ericallard** [comment]
+1 same here!!!

**Comment by jonmer85** [comment]
+1 same here!

**Comment by caarlos0** [comment]
+1 same here!

**Comment by negherbon** [comment]
+1 same here!

**Comment by erwindev** [comment]
+1

**Comment by manishas** [comment]
Working to resolve this. Update soon.

**Comment by Archana2015** [comment]
The issue is resolved. Thanks for your patience!

**Comment by Archana2015** [comment]
Some more detail on the issue: This was caused by a temporary grey out in our status processing. Builds were running fine, but status messages were not being processed and were getting queued up. It’s now resolved and everything’s back to normal.

**Comment by DanLipsitt** [comment]
I still get this error. It happens when I try to run the first branch build for a newly configured project. Are you sure the fix is deployed everywhere?

```
{"id":3000,"message":"No access or object not found for :id 5588824219a0550f0031ef7a","methodName":"chkPermForId|_getBuildById"}
```

**Comment by lekhab** [comment]
@DanLipsitt, The fix is deployed across the board. Can you please send your shippable.yml, so we can confirm if it is related to your specific project?

**Comment by DanLipsitt** [comment]
@lekhab, It turns out my shippable.yml was in the wrong place. I moved shippable.yml to the project root and now it's working. So the problem is that the error message doesn't tell you what's wrong. Should I open a separate bug for that?

**Comment by lekhab** [comment]
@DanLipsitt: yes, please open a separate bug for the error message. We are aware that the message isn't very helpful and this is on our backlog to fix.

**Comment by blakeblackshear** [comment]
I am seeing this error again when trying to start a build:
`{"id":3000,"message":"No access or object not found for :id 55897477ce9ab80b00d097f5","methodName":"chkPermForId|_getBuildById"}`

I dont get the error on the settings page though.

**Comment by phagunbaya** [comment]
Still getting below error but build started successfully.
```
{"id":3000,"message":"No access or object not found for :id 558c461fba27100b00eaf244","methodName":"chkPermForId|_getBuildById"}
```

**Comment by manishas** [comment]
This should be resolved, so closing. Please re-open if you run into this still. Thanks for your patience!
