### ISSUE TITLE
PHPUnit Testing several classes

### ISSUE THREAD

**Issue by molerat619** [Shippable/support#1947]
If I use Shippable for CI with PHPUnit, I do not know how to have several test-classes at a time. 

If I put all my tests in 1 class, it works fine and I get the reports and the sequence coverage. But if I want to have 2 test-classes, I don´t get the right reports.

**My structure:**

    - config
    - ...
    - tests
       - SQLTest.php
       - UserTest.php

**My shippable.yml**:

    language: php

    php: 
       - 5.4

    before_script: 
       - mkdir -p shippable/testresults
       - mkdir -p shippable/codecoverage
       - mysql -e 'create database if not exists test;'

    script:
       - phpunit  --log-junit shippable/testresults/junit.xml --coverage-xml shippable/codecoverage tests

**SQLTest.php**:

    class SQLTest extends PHPUnit_Framework_TestCase {
       public function testRandomStringLength(){
  	      $test = "string";

  	      $this -> assertEquals(strlen($test), 6);
       }
    }

**UserTest.php**:

    class UserTest extends PHPUnit_Framework_TestCase {
       public function testRandomStringLength(){
  	      $test = "string";

  	      $this -> assertEquals(strlen($test), 6);
       }
     }

The **log** on Shippable says:
    
     Time: 202 ms, Memory: 7.75Mb

     OK (2 tests, 2 assertions)

     Generating code coverage report in PHPUnit XML format ... done

The **build** is **successful**. But when I click the Tests-tab it says `No tests for this build.`. Why is that happening?

**Comment by rageshkrishna** [comment]
Hi @molerat619! I couldn't find any accounts with your github id in our system. Can you give me the github or bitbucket id you are using to log in to Shippable, or the id of a Shippable project or build that I can look at? Thanks!

**Comment by molerat619** [comment]
Hi I am logging in with molerat over BitBucket 
--
Best regards,
Marcel Izgin Mittwoch, 14 Oktober 2015, 08:41Vorm. -03:00 von Ragesh Krishna < notifications@github.com> :

**Comment by rageshkrishna** [comment]
I see your last build was triggered early yesterday morning. We had an issue with test report parsing that was fixed later in the day. Your build should now be able to parse test results correctly. Please try triggering another build and let me know how it goes.

**Comment by molerat619** [comment]
I triggered the old build and a new build and now both fail, even though the tests pass. In the tests-tab I still get no tests. But I get `Error parsing coverage reports.` in the log.

**Comment by rageshkrishna** [comment]
That's unusual. Can you send the coverage output file to me at ragesh@shippable.com so I can take a look at what's going on here?

**Comment by molerat619** [comment]
Please check your mailbox

**Comment by avinci** [comment]
@molerat619 we have pushed a fix to prod. Can you verify.

**Comment by molerat619** [comment]
@avinci I can confirm that it works! Thank you very much for the quick support
