### ISSUE TITLE
Errors during boot_container step

### ISSUE THREAD

**Issue by Gudahtt** [Shippable/support#2343]
We haven't updated our YML file since the updates - I wasn't aware there was a change being made. So our shippable.yml file doesn't have any "build" section - so I'm not quite sure what's going on in this boot_container step, or what config entry or setting might correspond with each command executed. Presumably there is still some level of support for the old config schema, as the builds are still running, though not without problems.

I'm seeing a number of errors during this step, and I'm not sure what they mean or what's causing them. Here is an example: https://app.shippable.com/runs/56dee3f62732f60d00b7e3be

```
echo 'Successfully configured registry credentials'
Successfully configured registry credentials


A client error (AccessDeniedException) occurred when calling the GetAuthorizationToken operation: User: arn:aws:iam::048100484699:user/s-shippable is not authorized to perform: ecr:GetAuthorizationToken on resource: *
```

```
sudo docker pull 690089443214.dkr.ecr.us-east-1.amazonaws.com/56968fd21895ca4474682f80:56968fd31895ca4474682f85
Pulling repository 690089443214.dkr.ecr.us-east-1.amazonaws.com/56968fd21895ca4474682f80

Please login prior to pull:
Username: EOF
```

```
echo 'Pulling cache image from registry failed, using default image'
Pulling cache image from registry failed, using default image
```

These errors appear to happen on every build. Any idea what's going on here? Thanks.

**Comment by Gudahtt** [comment]
It looks like the pull from cache is consistently failing.

I've tried migrating to the new config format and clearing the cache. Still the same result.

**Comment by manishas** [comment]
This should be resolved now. Please let us know if this happens again and we will reopen.

**Comment by Gudahtt** [comment]
I'm still seeing these three errors on every single one of our builds.

e.g. https://app.shippable.com/runs/56e1cd7abb39610c009219fc

**Comment by Gudahtt** [comment]
I tried with a branch using the new config format as well, just to be sure that wasn't the issue. Same result. Still can't pull from cache, still getting those same three errors.

https://app.shippable.com/runs/56e1cfa400d3410c00c49f9c

**Comment by ric03uec** [comment]
@Gudahtt there is an issue with caching and we're fixing it right now. i've disable cache for now on all projects and your builds seem to be running correctly.

@manishas re-opening this and updating the tags. this will be tracked with the bug that is in progress for fixing cache

**Comment by Gudahtt** [comment]
Sure, will do. Thanks.

**Comment by manishas** [comment]
We have deployed the new caching implementation to production. Docs have also been updated - http://docs.shippable.com/ci_configure/#caching-your-container

As mentioned in the docs, simply having a ```cache: true``` in the build section of the yml will result in $SHIPPABLE_BUILD_DIR being cached. You can also choose to cache specific folders using the `cache_dir_list` tag in addition.

```
build:
  cache: true
  # cache_dir_list is optional. If not present, we will cache $SHIPPABLE_BUILD_DIR.
  cache_dir_list: 
    - dir1
    - dir2
    - dir3
```
The first build you run with cache turned on might show an error during the upload cache step but the cache should be successfully pushed during the second build and be available thereafter.
