### ISSUE TITLE
Coverage badge not updating on GitHub

### ISSUE THREAD

**Issue by jeppefrandsen** [Shippable/support#2592]
### Is your request:

- [ ] A feature request: The feature you want currently does not exist. If implemented, will provide additional value to you.
- [X] A technical issue: You are unable to use Shippable's service per your expectation & need help to resolve the issue.
- [ ] A question: A non-technical question such as billing.

### Description of your issue:
I have some issues with the coverage badge on our GitHub page. The status badge is working fine but the coverage badge remains to be unknown even though it is X percent when viewing under Shippable settings. If I open the README.md with the atom editor it is also showed correct. 

When triggering a new build the status badge is updated right away. Are there any differences on how these two badges are generated which could cause this?

**Comment by stephanielingwood** [comment]
Hi @jeppefrandsen,

Thanks for your questions. To answer the second question first: the status badge mirrors the status of the most recent build, including in-process builds. This is why you see the badge update right away as it starts processing. The coverage badge, on the other hand, always reflects the most recent successful build for the branch specified (in the query string of the badge urls), so it won't update until a build succeeds.

As for the badge itself: would you mind checking the branch name in each badge url? Specifically, do the branches in the query string of all three badge urls (Shippable's project settings, the GitHub README you're looking at, and the README in atom) have at least one successful build with coverage? If the GitHub README url is referencing a branch with no successful builds, then you would see a badge with 'coverage unknown' in GitHub.

**Comment by jeppefrandsen** [comment]
Hi @stephanielingwood,

Yes, it has at least one successful build with coverage (latest 3 builds are with coverage). The exact same README.md is not working on GitHub but working in atom. If I copy the URL of the badge and paste it in e.g. the Safari browser it is also showed correctly.

**Comment by stephanielingwood** [comment]
HI @jeppefrandsen,

Thanks for checking...that helped narrow down the problem. Looks like we have a bug in how our cache-control header is being set for the coverage badges. We'll let you know when the fix is deployed.

**Comment by stephanielingwood** [comment]
Hi @jeppefrandsen,

The fix has been deployed, so the coverage badges shouldn't be cached in the future. GitHub still has a cache of your existing coverage badges, though. One way to force GitHub to clear its cache is to remove the coverage badge from your README, hard-refresh your repo's page on GitHub (just to be sure), and then add the coverage badge back to your README. That should destroy GitHub's existing cache of that image. 

Can you give this a try and let us know if you're still seeing problems? Sorry for any inconvenience this may have caused.

**Comment by jeppefrandsen** [comment]
Hi @stephanielingwood,

It is working perfect. Thank you very much.

**Comment by stephanielingwood** [comment]
@jeppefrandsen 

Hmm. I'm not able to reproduce the problem with my projects, so I'm curious as to why you're seeing this. Can you do me a favor? Next time you notice that the coverage badge is unknown in your README on GitHub, could you try doing these two things: 
- a hard-refresh of your GitHub repo page, and
- open the coverage badge link in its own browser tab, and see if that image matches the one in your GitHub repo

If the two images are the same, then you'll want to check that that branch specified in the coverage badge URL has previously had a successful build with coverage. (I know you looked at this before, but just in case...) Like I mentioned earlier, the coverage badge always uses the coverage percentages of the most recent successful build for that branch.

If the two images aren't the same, then the problem likely lies (again) with GitHub's image caching. In that case, are you noticing any similar behavior with the run status badge? 

Thanks in advance.

**Comment by jeppefrandsen** [comment]
Hi @stephanielingwood,

I tried to do a hard-refresh again but I still see the same issue using Safari on my iPhone. On my Mac everything is fine. If I keep reloading the page on my iPhone all coverage badges are suddenly unknown. If I keep reloading it will be correct at some point. The direct link to the badge is always working. The status badges are also always showed correct.

Is there a big difference between the status and the coverage badge caching? Thank you very much once again.

**Comment by stephanielingwood** [comment]
Hi @jeppefrandsen,

I just played around with my iPhone and a repo with coverage and a coverage badge, and was unable to reproduce this. I'm running iOS 9.3. What's the iOS version on your iPhone? Also, what browser/version are you using on your mac?

I confess I'm not much of an iOS expert, but I did notice that there were reports of Safari in iOS 8 not handling cache-control headers/etags correctly. I wonder if we're running into something related.

To answer your question, there should not be a difference between the status and coverage badge caching. They both have the same cache-control headers, and both use weak etags. The main difference between the two is when they are updated for a given build. Status badges are updated throughout a build, while coverage badges are updated after the build completes (and only if it is a green/successful build). If a build fails, the coverage badge will still reflect the coverage of the last successful build, whenever that was.

**Comment by jeppefrandsen** [comment]
Hi @stephanielingwood,

I am using iOS 9.3.1. I have the same issue on Chrome 50.0.2661.94 m (tried to clear the browsing history including cache and did not help). Internet Explorer seems to be working fine (at least now). But it is strange why the status badges are always showing the correct result.

**Comment by stephanielingwood** [comment]
Hi @jeppefrandsen,

Okay, we just deployed another change to the coverage badge cache-control headers to try to force it to stop caching those images. Can you take a look and see if that helped? Here's hoping... :)

**Comment by jeppefrandsen** [comment]
Hi @stephanielingwood,

Now it seems to work in all cases. Thank you very much once again.

**Comment by email2liyang** [comment]
@stephanielingwood , could you please help to check https://github.com/email2liyang/grpc-mate
the code coverage badge seems still not correct and cached by github.

**Comment by a-murphy** [comment]
@email2liyang Could you open a new issue with a link to your project on Shippable?  The link provided above only has a Coveralls coverage badge and I was unable to find your project on [Shippable](https://www.shippable.com).  This repository is for Shippable issues and we can only help with coverage results on, or reported by, Shippable.  

If this is about the Coveralls badge, you may also want to try the Coveralls support issues: https://github.com/lemurheavy/coveralls-public/issues
