### ISSUE TITLE
Cached Data Not Being Used in Builds

### ISSUE THREAD

**Issue by asans** [Shippable/support#2611]
- [ X ] A technical issue: You are unable to use Shippable's service per your expectation & need help to resolve the issue.

### Description of your issue:

I implemented caching into the shippable.yml file.  Based on the build console, it shows that shippable is tar'ing up the specified cache directories and uploading them to S3 for storage.  However, during the following run(s), restore_cache run is not finding the cached file and is saying `echo 'cache file not found, ignoring cache'`.

https://app.shippable.com/runs/5733f8346084320c003c4f01

Please note that I'm specifically caching certain directories under /root because some of the utilities we're running uses $HOME as the location for caching objects.  That caching portion seems to have no problems with this. 

Thanks for your help.

**Comment by manishas** [comment]
@stephanielingwood can you look into this?

**Comment by kanthchandra** [comment]
Hi @asans can you please try this now and let us know if it works?

There was some issues when the permissions got set for the bucket at our end and we have fixed that.

**Comment by asans** [comment]
A build just ran #230 and it still shows that cache file cannot be found.

See console logs here:

https://app.shippable.com/runs/5735f4a0a17f700b00cd4ba3

**Comment by kanthchandra** [comment]
Hi @asans can we trigger a few builds on your behalf and figure out what is going on?

**Comment by asans** [comment]
Sure. Go ahead

**Comment by manishas** [comment]
@balavignesh-s did you look into this? can you update status?

**Comment by balavignesh-s** [comment]
@manishas I looked into this and found the problem. This will be fixed early tomorrow.

**Comment by manishas** [comment]
where is the task to fix the problem? it should be linked to this issue.

**Comment by balavignesh-s** [comment]
@asans The problem was that the aws sdk did not use Shippable keys to upload the cache to s3. Rather it picked your keys, that you had set in the environment variables AWS_ACCESS_KEY_ID and AWS_SECRET_ACCESS_KEY. The default behavior of aws sdk is that if it finds environment variables named AWS_ACCESS_KEY_ID and AWS_SECRET_ACCESS_KEY, it will use them to make any calls. That's the reason why your cache was not restored. This is fixed now and will be a part of our next deployement.

**Comment by balavignesh-s** [comment]
@asans The fix is deployed. Can you please try now?

**Comment by asans** [comment]
This looks to be working.  However, now I'm seeing a similar issue with
another project of ours that's using cache but the cache is not found.  For
this project, no AWS credentials were used or set.

Here's the project's url:

https://app.shippable.com/runs/573bc3098706ea0c005c78b1

Thanks,
Alex

**Comment by kanthchandra** [comment]
Hi @asans , We were able to upload the cache in this build https://app.shippable.com/runs/573d4e20383ab70c00aa6cb2 so can you please trigger a couple of more builds and see if you still run into this?

**Comment by asans** [comment]
Looks good now!

You can close the request.
