### ISSUE TITLE
ADMIN POST: Critical issue with Shippable builds

### ISSUE THREAD

**Issue by manishas** [Shippable/support#3111]
We identified a security issue this morning which gave some user accounts elevated permissions. We have reviewed the logs and determined that no data breach occurred. 

As a precautionary measure, we have invalidated all your API tokens. The service is currently down and will be back up in 10 mins.

You need to do the following to get builds to work as expected when the service is back up: 
- A user who has access to the repository needs to re-login to Shippable 
- If you have manually created API tokens from the Shippable UI, you will need to recreate them

**Comment by mattclay** [comment]
@manishas It would be nice if the status page would reflect that the site is currently completely down, instead of showing only a partial outage.

**Comment by manishas** [comment]
@mattclay done.

**Comment by manishas** [comment]
We're still working on this... update soon.

**Comment by manishas** [comment]
everything should be back up and login should work now. Let us know if you run into any issues.

**Comment by mattclay** [comment]
@manishas I'm still seeing the error `Error getting account model: [object Object]`. Also, I'm still seeing SSL errors on https://shippable.com as well.

**Comment by djenriquez** [comment]
Hi Manisha,

Still the same for us also:
<img width="1440" alt="screen shot 2016-11-02 at 11 23 49 am" src="https://cloud.githubusercontent.com/assets/4636740/19941857/f182f99c-a0ee-11e6-9089-6fd47894199c.png">

**Comment by manishas** [comment]
Can you do the following:

- Click on logout and then login again
- Clear cookies and try to login again

**Comment by djenriquez** [comment]
Incognito mode works for me, looks like cookies do need to be cleared. Thanks 👍

**Comment by BlueDragonX** [comment]
Does this mean we will need to regenerate an API token for the resource event triggers we use to trigger deploys?

**Comment by mattclay** [comment]
Navigating to https://app.shippable.com/logout allowed me to then log in. However, I still must navigate directly to https://app.shippable.com/ due to SSL errors on https://shippable.com/.

**Comment by manishas** [comment]
@BlueDragonX yes, you will need to regenerate an API token for resource event triggers.

**Comment by thelamer** [comment]
Any advice on building the backlog of commits during the outage, I have many projects that are now synced and it has not triggered builds of the latest commits, am I missing something ?

**Comment by jdextraze** [comment]
Since I logged back as the email said, webhooks are called and says they are queuing a build, but no build is actually triggered.

**Comment by trriplejay** [comment]
@jdextraze this should be resolved now. Can you try again and let us know if builds are still not triggering? 

@thelamer any webhooks from github during the outage would have likely been ignored.  If you absolutely need builds for those commits, the best solution would be to go to the list of webhooks on the github repo, and re-send them. Otherwise, any new webhooks should trigger as normal for the latest commits.  Let us know if you're having other problems.

**Comment by manishas** [comment]
Closing this since it is resolved.
