### ISSUE TITLE
Cannot use SHIPPABLE_PHP_VERSION in image_tag

### ISSUE THREAD

**Issue by mbrodala** [Shippable/support#3292]
I just tried to use the `php` image for a build and have used `${SHIPPABLE_PHP_VERSION}-cli` as value for `image_tag` in `pre_ci_boot`:

```yaml
  pre_ci_boot:
    image_name: php
    image_tag: ${SHIPPABLE_PHP_VERSION}-cli
    pull: true
```

However, this value does not seem to be filled at this point:

```
boot_container
...
  sudo docker run -d ... php:-cli
Unable to find image 'php:-cli' locally
Pulling repository docker.io/library/php
Tag -cli not found in repository docker.io/library/php
```

If this is not supported, how else would I go about running multiple jobs with different PHP versions?

**Comment by rageshkrishna** [comment]
This will be fixed by https://github.com/Shippable/support/issues/3224, which should be available by the end of the week.

Closing as duplicate.

**Comment by mbrodala** [comment]
It looked similar indeed, just wanted to be sure it *is* the same issue, thanks. ;-)

**Comment by kanthchandra** [comment]
@mbrodala This has been fixed with the latest release and you will be able to use env variables in pre_ci and pre_ci_boot sections. So please try it out and let us know if it works for you.

**Comment by mbrodala** [comment]
I just retried and it still does not work, I get [exactly the same error](https://app.shippable.com/runs/5885bcf23b7d560f0092831d/1/console).

**Comment by mbrodala** [comment]
Notice that I've just used an env variable in `image_name` just fine.
