### ISSUE TITLE
Error in aws_eb_deploy

### ISSUE THREAD

**Issue by sumothecat** [Shippable/support#3318]
### Shippable errors during its build step aws_eb_deploy - missing libyaml dependency?

- Link to the build failure  https://app.shippable.com/runs/588745e4b98c6c0f00f23b82/1/console
- Scripts called from the yml (optional)  Please see shippable.yml in https://github.com/jncc/deli/tree/dockerless

The application deploys fine from local dev using `eb deploy`

**Comment by a-murphy** [comment]
This looks like a duplicate of #3316.  Basically, `awsebcli` is failing to install because of a problem with its dependencies.  There's not much that we can do, but adding `pip install setuptools==34.0.1` to the end of your `ci` section after `botocore` should help until the dependency problems are resolved.

**Comment by abhijitkini** [comment]
closing since the question is resolved

**Comment by sumothecat** [comment]
Hi, thanks but this doesn't fix. https://app.shippable.com/runs/58886f0a3b653a0f00fbcc26/1/console
