### ISSUE TITLE
clang++ is broken

### ISSUE THREAD

**Issue by DronMDF** [Shippable/support#3409]
I add clang to build matrix.
g++ is worked fine.
clang++ cannot find -lstdc++

https://app.shippable.com/runs/58b72384ddd8e8070046edd5/2/console

My yml file:
https://github.com/DronMDF/goost/commit/6259e6581eae0ee00207080188357cd39c75f566

**Comment by avinci** [comment]
@rageshkrishna can we get this fixed too as we are building the image again

**Comment by rageshkrishna** [comment]
This is already working without any issues in the new images.

@DronMDF We're releasing new images on Monday that will resolve this. If you would like to try out the cutting edge images right away, you can use `drydock/u14cppall:master`.

I'll keep this issue open until we launch the images on Monday so I can update it with the latest tag name.

**Comment by DronMDF** [comment]
Thanks. i'll try it on Monday.

**Comment by DronMDF** [comment]
drydock/u14cpp:prod is not work...
https://app.shippable.com/runs/58bdbddbc2fe0105009690fc/2/console

i need use drydock/u14cppall?

**Comment by stephanielingwood** [comment]
Hi @DronMDF,

Sorry about this - we've delayed our release a little for issues that are unrelated to the images. However, the `drydock/u14cppall:master` image is our current release candidate, and will, in all likelihood, be what is officially released later this week. 

So, for now, yes - you can use `drydock/u14cppall:master`, and it should work. We'll let you know when the official release happens.

**Comment by avinci** [comment]
we released new version of images just now. Please set your subscription to use `v5.3.2` version of system images on your subscription settings page to get the latest image for cpp.

**Comment by DronMDF** [comment]
How i can set version of images?
I'm using drydock/u14cppall:prod
This is a wrong?

Build still failed.

**Comment by rageshkrishna** [comment]
@DronMDF Here's what you need to do:

1. Go to the "Settings" tab on your subscription (not the project)
1. In the "Machine Images" panel, select "v5.3.2" from the dropdown. This will get your builds to run on the new AMI that has all the new drydock docker images already pulled locally.
1. Update your project's shippable.yml file to include the following image settings to use the latest drydock image for your project:
    ````
    build:
      pre_ci_boot:
        image_name: drydock/u16cppall
        image_tag: v5.3.2
    ````

**Comment by DronMDF** [comment]
Thanks... Machine images is work.
