### ISSUE TITLE
Shippable repository not detecting changes; cannot build new resources (urgent)

### ISSUE THREAD

**Issue by Jsgoller1** [Shippable/support#3511]
### Description of your issue:
We have all of our pipeline / resource / etc files stored in a repository called `shippable-pipelines`. Normally, Shippable picks up on changes to the `master` branch and automatically runs the rsync job to pull in the changes. However, despite having not made any changes to our account settings, the rsync job won't start automatically when we merge to `shippable-pipelines/master`. Additionally, when we run the job manually, it doesn't see any of the changes we've merged to the repository since the automatic runs stopped happening. The rsync job exits successfully despite this and is marked `green`.

This is a breaking issue for our team and we need to get it solved immediately, given that our CD infrastructure depends on Shippable.

**Comment by ambarish2012** [comment]
@Jsgoller1 we are investigating.

**Comment by Jsgoller1** [comment]
@ambarish2012 thanks - please let me know if you need any additional information from us.

**Comment by Jsgoller1** [comment]
@ambarish2012 The webhook still exists, and shows a `recent delivery` from `2017-04-12 12:57:51` with a 200 response, and numerous similar ones previously. The webhook has `push`, `release`, and `pull request` permissions.

**Comment by ambarish2012** [comment]
@Jsgoller1 thanks, we are investigating with high priority.

**Comment by ambarish2012** [comment]
@Jsgoller1 please can you give us the SHA of your most recent merge?

**Comment by Jsgoller1** [comment]
@ambarish2012 `0d70809e6d51f98355beaf66463c96257e352c10`

**Comment by ambarish2012** [comment]
@Jsgoller1 we managed to trigger rsync with that SHA and it is now picking up the merged changes. It failed though, please can you take a look.

**Comment by ambarish2012** [comment]
@Jsgoller1 we found the root cause of your issue and will be deploying the fix tonight. Until the fix is in PROD, we will have to manually trigger your rsync job using the SHA's.

**Comment by Jsgoller1** [comment]
Alright, thank you for the quick turnaround. I guess until your fix is in tonight, I can post SHAs here and you will report them internally?

**Comment by ambarish2012** [comment]
Yes - we will apply your SHA's once you post them. Thanks for bearing with us.

**Comment by Jsgoller1** [comment]
@ambarish2012 `9bf060512ca8bd56c7fe62900078a1ecdc0954f1`

**Comment by ambarish2012** [comment]
@Jsgoller1 thanks on it.

**Comment by ambarish2012** [comment]
@Jsgoller1 we deployed the fix to PROD last night. Thanks!

**Comment by Jsgoller1** [comment]
@ambarish2012 we are still seeing this issue for a separate repository (this time our `ops-pipeline` repository under the same subscription). This issue needs to be re-opened, and `bc841b4320c4523e2dc8237ac027cec9994af653` needs to be deployed.

**Comment by Jsgoller1** [comment]
Thanks again for the quick turnaround!

**Comment by ambarish2012** [comment]
@Jsgoller1 investigating.

**Comment by ambarish2012** [comment]
@Jsgoller1 the rsync job last on 04/07 and failed with the error - Fetching YML files
Failed to get YML files with error: true.

I just want to confirm that you merged a change today that potentially fixes the rsync failure encountered on 04/07.

**Comment by ambarish2012** [comment]
@Jsgoller1 please could you check the following -

1. YML files exist for the pipeline.
2. Permissions on the YML files. 

We are seeing an error on our side fetching the YML files - github error 422.

common|github|getFilesForPatternList|projectFullName:zenreach/ops-pipeline|commitSha:a56a635511f3c50b1f378c5bac321f0ae3ffe0bc|_getFilePaths Failed to get Tree for repo: ops-pipeline with error: 422

**Comment by ambarish2012** [comment]
@Jsgoller1, we discovered a new bug, which was caused due to an error processing the previous SHA on 04/07. We have manually triggered the rsync job. 

Please note that you won't encounter this bug again, since we have processed your SHA correctly now and so the diff with your next commit SHA will be accurately handled.

**Comment by ambarish2012** [comment]
I will close this issue and open a new issue since we are seeing a different bug.

**Comment by ambarish2012** [comment]
Tracking this problem in issue [3521](https://github.com/Shippable/support/issues/3521) and closing this issue.

**Comment by Jsgoller1** [comment]
@ambarish2012 thanks for your help; confirming that the most recent build is green.
