### ISSUE TITLE
Long queue duration

### ISSUE THREAD

**Issue by mbrodala** [Shippable/support#3756]
ATM we are seeing very long queue durations, e.g. build 1129 of project 58ab0bf60bfe57100058d7a6 currently is at 12 minutes and has yet to start.

We are using BYON and until last week had queue durations of a few seconds.

What's wrong here?

**Comment by mbrodala** [comment]
The mentioned build has now started after 18 (!) minutes waiting in the queue. There where enough minions available which could have handled it.

**Comment by rageshkrishna** [comment]
@mbrodala We're looking in to this right now. I can confirm that the job queuing service was backed up for a few minutes which caused a few jobs to wait much longer than usual. I'll share more details soon.

**Comment by rageshkrishna** [comment]
@mbrodala The queuing service was functioning unusually slowly for roughly 30 minutes. This caused a large number of builds to get stay in a queued state. We have reset the service and the queues have now cleared up. You should see your builds being triggered normally at this point in time.

**Comment by mbrodala** [comment]
Yes, I can confirm that the queue times have returned to normal (< 5 sec).

**Comment by mbrodala** [comment]
It seems like the issue has returned, could you have another look?

And maybe the queue service could be added to http://status.shippable.com/ ?

**Comment by jefffleming** [comment]
I'm also experiencing this issue.  Is there an update?

**Comment by codypperson** [comment]
Any update here? All of our jobs have pretty much come to a complete halt.

**Comment by rageshkrishna** [comment]
We've identified the root cause and are working on a fix. I'll have more updates on this issue soon.

**Comment by mbrodala** [comment]
Here are some details: http://status.shippable.com/incidents/8jyc1dkhpg4x

**Comment by rageshkrishna** [comment]
Earlier today we deployed a patch to our queuing system that resolves this issue. We have improved payload handling in the job queue to ensure that we do not run in to this issue again. We are continuing to monitor the system closely today and have not seen any delays in triggering jobs since the patch has been deployed.

I'm closing the issue as the root cause has been addressed. Please reopen if you continue to see problems.

**Comment by mbrodala** [comment]
I cannot reopen this issue but I'm still seeing queue delays ATM.

**Comment by mbrodala** [comment]
See #3767 for updates.
