### ISSUE TITLE
Issues with gitRepo resource with specified branch

### ISSUE THREAD

**Issue by vidiecan** [Shippable/support#4553]
Resource Id: 82617

yml:
```
name: te_x_Repo
type: gitRepo
integration: Bitbucket integration
pointer:
  sourceName: y
  branch: a_name
  buildOnPullRequest: true
flags:
  - te_master_rSync
```

Issue(s):
1. I do not see all the commits from the `a_name` branch in the versions (e.g., 8842970);
1. I see commits (commit hashes e.g., 33e2fb4d0d0e73b759706936ef344fc3436750fe ) from other branches;
1. *Observation*: The versions on shippable show the correct time (e.g., Today at 12:23 PM and match the commit time) but they pop up on the page only after runCI finishes - in other words, they were not at the page visible before 12:40.

Versions from https://app.shippable.com/subs/.../resources/te_x_Repo/versions
```
75 | 33e2fb4d0d0e73b759706936ef344fc3436750fe | Today at 12:23 PM | N/A | fighting shippable
74 | 322f7bd47f11197f0e60937547f687ba47fcd2f6 | Yesterday at 7:40 PM | N/A | fighting shippable
73 | 8513941860c8936f01d3ea5f192d536528f98785 | Yesterday at 6:36 PM | N/A | ci: buildOnPullRequest: true
72 | 650395c990b3ee050467f49c0a905ebb52f76478 | Yesterday at 6:35 PM | N/A | Merge branch 'master' into a_name
71 | 8513941860c8936f01d3ea5f192d536528f98785 | Yesterday at 6:34 PM | N/A | ci: buildOnPullRequest: true
```

But in bitbucket in commits for branch `a_name` I see
```
| 8a8ae34 | fighting shippable Branches a_name| 40 minutes ago | Success
| 8842970 | fighting shippable Branches a_name| 42 minutes ago | Success
| e4ea0d5 M | Merge branch 'master' into a_name Branches a_name | 16 hours ago | Success
| e092650 | fighting shippable | 16 hours ago |  
| 90b4615 M | Merge branch 'master' into a_name Branches a_name | 16 hours ago | Success
| 7ef2b4b | fighting shippable | 16 hours ago |  
| 2032e9e | revert back Branches a_name | 17 hours ago | Success
| 04eb7a7 M | Merge branch 'master' into a_name Branches a_name | 17 hours ago |  
| 322f7bd | fighting shippable | 17 hours ago | Success
```

Look for `322f7bd ` to have a fixed point in those two lists.

**Comment by trriplejay** [comment]
It looks something changed your branch from `a_name` to `master`, though I see that your yml is correctly defined..  For now I've corrected your resource, and we'll continue to investigate the root cause.

**Comment by trriplejay** [comment]
closing as dup of https://github.com/Shippable/support/issues/4537

**Comment by vidiecan** [comment]
@trriplejay should the latest release solve this issue? 

We are still having problems with our pipelines because rSync jobs have not been triggered while the ciRepo ones have and that is because the version on the gitRepo has not been correctly updated.

rSync job - Job Id: 39197 
```
name: c-image-to-text_master_rSync
type: rSync
steps:
  - IN: c-image-to-text_master
  - TASK: managed
flags:
  - wtf
  - c-image-to-text_master_rSync
  - c-image-to-text_master_rSync
```

Resource Id: 39196
```
name: c-image-to-text_master
type: syncRepo
pointer:
  sourceName: mazoea-team/c-image-to-text
  branch: master
integration: uff
flags:
  - wtf
  - c-image-to-text_master_rSync
  - c-image-to-text_master_rSync
defaultFlag: c-image-to-text_master_rSync
```
Last version
```

118 | 4efad66fbfbee6aae49eb09269cd22ad2f60fe47 | Last Wednesday at 7:39 PM | N/A | new version | More
```
but all versions (cca 8) since (`Wed Sep 12 19:39:26 2018 +0200`) are missing.

**Comment by trriplejay** [comment]
hmm, that repo actually looks like it is configured correctly.  Typically syncRepos will only get a new version if the Shippable `yml` files are modified.  If you make other changes, then rSync is not expected to run.  Can you confirm that making a change to a `shippable.yml` configuration file does not trigger the rSync job?

**Comment by vidiecan** [comment]
@trriplejay re-tried and now it works, hopefully it stays this way. 

for the record, I updated `.shippable.yml` three times today and only the last one (few minutes ago) triggered rSync.

**Comment by vidiecan** [comment]
@trriplejay we are experiencing similar issue again,

Job Id: 86347
has not been triggered by its IN resource
```
  - name: te_code_quality
    type: runSh
    steps:
      - IN: te_Repo
      - TASK:
```
The last time it was triggered by te_Repo was on `09/21/2018`.

However, re_Repo has all the versions 
```
79 | dc0e1784e505753ae2258decea22809eb6628641 | Today at 2:22 PM | N/A | moving codequality back to runSh | More
78 | 92345b8dbacba498481e8fc48eb24ade0496b71a | Today at 2:15 PM | N/A | devOps: testing and fighting again | More
77 | 9ff6110cf8aa6b15ab15b778ddc1c1c85a14e000 | Today at 2:03 PM | N/A | devOps: testing and fighting again | More
76 | 0b99c9a93674e50cb07542c40dfb162bca26b26c | Today at 12:57 PM | N/A | devOps: fighting docker -v again | More
75 | 75a38d5f4df3ecce9ff2b4091b41a2de7f623174 | Today at 12:47 PM | N/A | devOps: fighting docker -v again | More
74 | c2b9284f8f5442893596317d43c35fcef11b49c4 | Today at 10:25 AM | N/A | devOps: debugging shippable
73 | 7aacd82daaac8a958b78acdbef69c234c7ca4217 | 09/21/2018
```

**Comment by trriplejay** [comment]
hmm, since you've made this comment, it looks like it has actually run twice as a result of an update to the repo...  is it possible that the job was paused? Was any other change made after your comment that got it working again?

**Comment by vidiecan** [comment]
@trriplejay I only commented the issue here and it started to work ;)
