### ISSUE TITLE
[Consolidated feature request] Push to docker registry feature requests

### ISSUE THREAD

**Issue by moylop260** [Shippable/support#824]
I have dedicated host configured done.
All works fine.

Now, I need connect to my minion build container to debug my test.
With other tools ci we can enable "ssh connection" for this purpose.

![example_ci](https://cloud.githubusercontent.com/assets/6644187/5220263/2c3caedc-7628-11e4-974b-13f042f9045c.jpg)

However, shippable use docker container.
Can we use this docker container built by shippable?

**Comment by moylop260** [comment]
@rageshkrishna 
What do you think of your last comment: https://github.com/Shippable/support/issues/824#issuecomment-64857719?

**Comment by manishas** [comment]
Current set of requests -

- Push PR build images to Docker registry
- Create multiple tags for each build
- Supply an after_push trigger where customers can specify where to deploy the pushed container

**Comment by moylop260** [comment]
Oh my god! :+1: 
Really?

**Comment by manishas** [comment]
@moylop260 I think you misunderstood :) I am consolidating all related feature requests so that we can tackle them together when we start working on this area :)

**Comment by moylop260** [comment]
Oh I got it, sorry.
The first point is right!
The second point 
The third point I don't told that but is a good point.


- [ ] Push PR build images to Docker registry. Yes, this is my point is this issue.
- [x] Create multiple tags for each build. I saw that this is fixed [here](https://github.com/Shippable/support/issues/1221)
- [ ] Supply an after_push trigger where customers can specify where to deploy the pushed container. I don't saw this point. But is a good point.

**Comment by imothee** [comment]
Just like to add my support to an after_push event. We currently have to do
CI -> tests -> artifact build -> Docker build (we use scratch and only put the binary in the Docker image) -> push to docker hub.

We really want this to call ECS/Google Container Engine after the image has been pushed to the registry. We can't build on anywhere else because of the custom dockerbuild requiring the artifacts.

**Comment by rvrignaud** [comment]
Hello @moylop260 and @manishas,
I don't see how "Create multiple tags for each build" is fixed by [this issue] (https://github.com/Shippable/support/issues/1221) : this is a change of tag name strategy.
If I am not wrong, multiple tags for each build is a feature ask by @marcospedreiro and myself [here] (https://github.com/Shippable/support/issues/1176#issuecomment-113296512) : support of build num or shacommit and latest as docker tag for instance.

Regards,

**Comment by marcospedreiro** [comment]
+1 @rvrignaud . The feature we are requesting should allow someone to build an image and push two (or more) tags to a repo. As an example I would like to be able to push an image with it's build number, and a tag 'devlatest.'

I would also like to request a feature to allow unique tags per branch. So in the shippable.yml file for example I could specify:

```
branch: master
  tags: stablelatest
branch: new_feature
  tags: devlatest
```

So whenever someone merges to master, a new stable build is made, and new features can be tested in a dev environment without causing any confusion with the tags.

**Comment by manishas** [comment]
@rvrignaud multiple tags issue is not fixed. I am tracking all feature requests related to pushing docker images to a registry in this issue so that we can tackle it as a feature area rather than tracking as several separate issues. 

So I changed the name of this issue to a consolidated feature request. None of the 3 issues (multiple tags, push to registry for PR builds, after_push trigger) are done. They're high on our priority list though.

**Comment by leonfs** [comment]
Is there any news about the state of this feature requests? after_push trigger would be Fantastic!!

**Comment by nlf** [comment]
I'd like to put in a request to be able to build when a tag is pushed to git, and to be able to tag the docker build with the same tag name that was received from git somehow.

**Comment by hshira** [comment]
The multiple tags on docker build is a high priority issue for us. 
We need the tag each docker image with -- 
(1) build number and 
(2) latest
Please let us know when you will be able to do this?

**Comment by avinci** [comment]
I am going to open a new issue on this feature and closing this.
